<!doctype html>
<html class="no-js" lang="ja">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134228602-13"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134228602-13');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>😇 👨 🚁 「みんなのためのCAD、無料、そして誰も手放さない...」またはPythonでのFreeCADプログラミングの最初のステップ 🚨 👩🏿‍✈️ 🤸🏼</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="おそらく、NanoCADの例を使用したCADプログラミングの最初のステップに関する私のノートにすでに出くわしたのでしょう。
 
 「電子カルマン」のレベルでプログラムする方法を知らず、CADを知っている人にとって、それは驚くべき冒険でした。ただし、NanoCADは主に商用製品です。その無料版は約6年...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script>document.write('<script src="//pagea' + 'd2.googles' + 'yndication.com/pagea' + 'd/js/a' + 'dsby' + 'google.js"><\/script>')</script>
  <script>
        var superSpecialObject = {};
        superSpecialObject['google_a' + 'd_client'] = 'ca-p' + 'ub-6974184241884155';
        superSpecialObject['enable_page_level_a' + 'ds'] = true;
       (window['a' + 'dsbygoogle'] = window['a' + 'dsbygoogle'] || []).push(superSpecialObject);
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://geek-week.github.io/index.html"></a>
    <div class="page-header-text">Get best of the week</div>
  </header>
  <section class="page js-page"><h1>「みんなのためのCAD、無料、そして誰も手放さない...」またはPythonでのFreeCADプログラミングの最初のステップ</h1><div class="post__body post__body_full">
      <div class="post__text post__text-html post__text_v1" id="post-content-body" data-io-article-url="https://habr.com/ru/post/464113/"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">おそらく、NanoCADの例を使用したCADプログラミングの最初のステップに関する私のノートにすでに出くわしたのでしょう。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
「電子カルマン」のレベルでプログラムする方法を知らず、CADを知っている人にとって、それは驚くべき冒険でした。</font><font style="vertical-align: inherit;">ただし、NanoCADは主に商用製品です。</font><font style="vertical-align: inherit;">その無料版は約6年間更新されておらず、開発の機会に関しては時代遅れになっています。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
しかし、私は本当に素晴らしい物語のように、</font></font><i><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">「すべての人の幸せを無駄にして、誰も気分を害させないでください！」</font></font></i><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">。</font><font style="vertical-align: inherit;">そのため、同志の忠告に耳を傾けることになった</font></font><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u=" class="user_link"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Drzugrik</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">FreeCADを自分でインストールします。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
それで、私はあなたのために資料を書いています。たった1日で、このCADソフトウェアをAnacondaと友達にする方法を学び、テキストで小さな四角形を描く簡単なスクリプトをPythonで記述し、WindowsとLinuxでの動作をテストしました。</font><font style="vertical-align: inherit;">あなたがそれを行うことができるように、私が実際に段階的に説明する準備はできていますか？</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
PythonとFreeCADの魅力的なカップルを知りたいですか？</font><font style="vertical-align: inherit;">その後、猫の下で大歓迎です。</font></font><br>
<br>
<img src="https://habrastorage.org/webt/zb/s6/qb/zbs6qbcrm_xvuqlv5mcov7zo8js.png"><br>
<a name="habracut"></a><br>
<a name="I"></a><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
内容：</font></font><br>
<br>
<a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">パートI：はじめに。</font></font></a><br>
<a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">パートII：標準インストールと最初のテスト</font></font></a><br>
<a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">パートIII：そして、「アナコンダ」とFreeCadの友達を作ります</font></font></a><br>
<a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">パートIV：シンプルなライブラリを作成します</font></font></a><br>
<a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">パートV：結論</font></font></a><br>
<br>
<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> パートI：はじめに </font></font></h4><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
奇妙なことに、HabréではFreeCADに関する出版物はほとんどありません。 </font></font><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u=" class="user_link"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Eddy_em</font></font></a> <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">“ Meet：FreeCAD”</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">、そして私たちの記事のヒーローが</font><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="><font style="vertical-align: inherit;">ついに</font></a><font style="vertical-align: inherit;">言及されているいくつかの作品。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
まず、プログラムについてたった2語です。</font><font style="vertical-align: inherit;">公式</font></font><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Webサイトの</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">情報を複製するのではなく、</font><font style="vertical-align: inherit;">このCADに注意を向けた理由を大まかに説明します。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
したがって、FreeCADはオープンソースのコンピューター支援設計システムであり、主に3次元パラメトリックモデリングに焦点を当てています。執筆時点では、プログラムの最新バージョンは0.18.3です。リリース番号の値が1とはほど遠いことを混同しないでください。 FreeCADは長く活発に開発されており、現在は非常に機能的です。さらに、長い間理解しているように、3Dモデリングと印刷に携わる人々の間で、特にオープンソース/オープンハードウェアとあらゆる種類のDIYに興味がある自作のイデオロギー的人々の間で、一定の人気があります。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
しかし、突然3Dモデリングをまったく理解できなくなった場合、これはFreeCADをバイパスする理由にはなりません。</font><font style="vertical-align: inherit;">CAD機能は特定のモジュールに分かれています-ワークベンチには、シートフレームを装飾するためのワークベンチやBIMコンセプトを実装するためのワークベンチなど、通常の2D図面があります。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
実際には、プログラムには「ワゴンと小さなカート」がありますが、今日は「食欲を刺激する」ためだけに、完全に原始的なことをしようとします。</font></font><br>
<a name="II"></a><br>
<br>
<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> パートII：標準インストールと最初のサンプル </font></font></h4><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
FreeCADは3つの一般的なオペレーティングシステムすべてで利用できますが、「アップル」の手法を利用できないため、Windows 10とLinux Mintのオプションのみを検討します。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
FreeCADのプログラミングを開始する最も簡単な方法は、配布キットをダウンロードして、オペレーティングシステムの標準的な方法でインストールすることです。この場合、（Pythonの記事のバージョン3.6.6を書いている時点で）プログラムと共にPythonインタープリターがプリインストールされています。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
NanoCADやAutoCADよりもFreeCADのプログラミングを開始する方が簡単です。[表示]タブ-&gt; [パネル]を開き、Pythonコンソールをオンにするだけです。実際、これですべてです。安全にプログラミングできます。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
しかし、最初に、通常の方法で何かを描いてみましょう。たとえば、円。</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
コンソール出力に注意してください</font></font><br>
<br>
<pre><code class="python hljs">Gui.activateWorkbench(<span class="hljs-string">"DraftWorkbench"</span>)
<span class="hljs-meta">&gt;&gt;&gt; </span>App.newDocument(<span class="hljs-string">""</span>)
<span class="hljs-meta">&gt;&gt;&gt; </span>App.setActiveDocument(<span class="hljs-string">"____________________"</span>)
<span class="hljs-meta">&gt;&gt;&gt; </span>App.ActiveDocument=App.getDocument(<span class="hljs-string">"____________________"</span>)
<span class="hljs-meta">&gt;&gt;&gt; </span>Gui.ActiveDocument=Gui.getDocument(<span class="hljs-string">"____________________"</span>)
<span class="hljs-meta">&gt;&gt;&gt; </span>Gui.activeDocument().activeView().viewDefaultOrientation()
<span class="hljs-meta">&gt;&gt;&gt; </span><span class="hljs-keyword">import</span> Draft
<span class="hljs-meta">&gt;&gt;&gt; </span>pl=FreeCAD.Placement()
<span class="hljs-meta">&gt;&gt;&gt; </span>pl.Rotation.Q=(<span class="hljs-number">0.0</span>,<span class="hljs-number">0.0</span>,<span class="hljs-number">1.5308084989341915e-17</span>,<span class="hljs-number">1.0</span>)
<span class="hljs-meta">&gt;&gt;&gt; </span>pl.Base=FreeCAD.Vector(<span class="hljs-number">-1.0610677003860474</span>,<span class="hljs-number">-0.31207874417305</span>,<span class="hljs-number">0.0</span>)
<span class="hljs-meta">&gt;&gt;&gt; </span>circle = Draft.makeCircle(radius=<span class="hljs-number">0.8633861373365326</span>,placement=pl,face=<span class="hljs-literal">False</span>,support=<span class="hljs-literal">None</span>)
<span class="hljs-meta">&gt;&gt;&gt; </span>Draft.autogroup(circle
</code></pre><br>
<img src="https://habrastorage.org/webt/de/z5/tj/dez5tjh3qiturpqcdegtzclmwtq.png"><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
FreeCADはフードの下で何も隠さず、円を描くためのすべての主要な操作がコンソールに表示されます。</font><font style="vertical-align: inherit;">コードをコピーして、少し右に2つ目の円を描くこともできます。</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
変数を入力して別の円を描きましょう。コンソールの出力をコピーし、1行ずつ貼り付けて小さな変更を加えます。</font></font><br>
<br>
<pre><code class="python hljs">x=<span class="hljs-number">-1.0610677003860474</span><font></font>
pl=FreeCAD.Placement()<font></font>
pl.Rotation.Q=(<span class="hljs-number">0.0</span>,<span class="hljs-number">0.0</span>,<span class="hljs-number">1.5308084989341915e-17</span>,<span class="hljs-number">1.0</span>)<font></font>
pl.Base=FreeCAD.Vector(x*<span class="hljs-number">5</span>,<span class="hljs-number">-0.31207874417305</span>,<span class="hljs-number">0.0</span>)<font></font>
circle = Draft.makeCircle(radius=<span class="hljs-number">0.8633861373365326</span>,placement=pl,face=<span class="hljs-literal">False</span>,support=<span class="hljs-literal">None</span>)
</code></pre><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ご覧のとおり、2つの円があり、計画どおり、最初の円の基点の座標「x」の右側に1を乗算したものが5倍されています。</font></font><br>
<br>
<img src="https://habrastorage.org/webt/ma/gc/gj/magcgjk1bliuyetenjwldcxsm9a.png"><br>
<br>
<a name="III"></a><br>
<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> パートIII：Anacondaで友達をFreeCadにしましょう </font></font></h4><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
しかし、CADの機能は、「カルマン」としての標準的な使用に限定されません。 APIを使用して、FreeCADを独自のプログラムに統合し、グラフィカルインターフェースの有無にかかわらず使用できますが、この問題については改めて検討します。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
それまでの間、この状況を想像してみてください。たとえば、Pythonでの機械学習とデータ分析が好きで、</font></font><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Anacondaディストリビューションキット</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">をすでにインストールしている</font><font style="vertical-align: inherit;">としましょう。conda-forgeの皆さんのおかげで、このディストリビューションキットとFreeCADのすべての機能を組み合わせることができることを非常に嬉しく思います。</font><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="><font style="vertical-align: inherit;">リンクは、</font></a><font style="vertical-align: inherit;">あなたがミニcondaを使用して、我々はそのナビゲーターを通じて本格的な「アナコンダ」にインストールする場合は、それをインストールする方法についてのガイダンスを提供します。</font></font><br>
<br><font style="vertical-align: inherit;"></font><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="><font style="vertical-align: inherit;"></font></a><font style="vertical-align: inherit;"></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
そのため、Anaconda-Navigatorを開き、[ </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">環境</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> ]タブに移動し、[ </font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">作成</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> ]ボタンをクリックして新しい環境を</font><b><font style="vertical-align: inherit;">作成し</font></b><font style="vertical-align: inherit;">ます</font><font style="vertical-align: inherit;">。環境の名前は、自由に付けることができます。「freecad」と呼んでいます。 Pythonの必要なバージョンを選択し、新しい環境を作成します。</font></font><br>
<br>
<img src="https://habrastorage.org/webt/nz/vk/tx/nzvktxdb67ksyfosfvofnzthufa.png"><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
しかし、これだけでは不十分です。conda-forgeチャネルを追加する必要があります。</font><font style="vertical-align: inherit;">「</font></font><b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">追加</font></font></b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">」</font><font style="vertical-align: inherit;">ボタン</font><font style="vertical-align: inherit;">「conda-forge」を</font><font style="vertical-align: inherit;">クリックした後に表示されるフィールドに入力して</font><font style="vertical-align: inherit;">、システムにパッケージのリストを更新させるだけです。</font></font><br>
<br>
<img src="https://habrastorage.org/webt/fo/zm/ez/fozmezgon_6gv-expuoi-obcpaq.png"><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
これでFreeCAD自体をインストールする準備がほぼ整いました。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
パッケージの名前でLMBをクリックし、次の図のように、インストールするバージョンを選択します</font></font><i><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">（本当にインストール済みです）。</font></font></i><br>
<br>
<img src="https://habrastorage.org/webt/kb/zq/o6/kbzqo6mjl3h6i7xnieahzwkf6x4.png"><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
面倒な待機の後、FreeCad配布パッケージがインストールされ、必要なバージョンを起動するだけで済みます。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
最も単純なケースでは、起動パラメーターなしで、環境でcondaコンソールを起動し、同じ名前のFreeCADコマンドでCADを起動する必要があります。</font></font><br>
<br>
<img src="https://habrastorage.org/webt/hd/hl/pf/hdhlpflqpsvwlwva52gq4hpifyk.png"><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
空のFreeCADウィンドウが開き、2次元図面用のワークベンチを選択します。</font></font><br>
<br>
<img src="https://habrastorage.org/webt/cq/wy/bu/cqwybuzqdedz5hinrqgabwh-ygg.png"><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ご覧のとおり、Pythonのバージョンは標準インストールのバージョンとはまったく異なります。</font></font><br>
<img src="https://habrastorage.org/webt/qm/fb/dt/qmfbdtthhkn8xd2l9_ldszuqwyc.png"><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
新しいドキュメント（Control + N）を作成してみましょう。ミニライブラリのテストに役立ちます。</font></font><br>
<br>
<a name="IV"></a><br>
<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> パートIV：単純なライブラリの作成 </font></font></h4><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
私たちのライブラリは原始的です。</font><font style="vertical-align: inherit;">基本的に、ユーザーが指定した任意のテキストが入力される長方形を描画するコマンドを作成します。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ファイルを作成し</font></font><i><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">（私は「drawhabr.py」と呼び</font></font></i><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">ます</font><i><font style="vertical-align: inherit;">）</font></i><font style="vertical-align: inherit;">、次のコードをその</font><font style="vertical-align: inherit;">ファイルに</font><font style="vertical-align: inherit;">書き込みます。</font></font><br>
<br>
<pre><code class="python hljs"><span class="hljs-comment">#Simple lib for test Python API in FreeCad</span>
<span class="hljs-comment">#Tested on Python 3.7. and FreeCad 0.18.3</span>
<span class="hljs-comment">#Designed for article - https://habr.com/ru/post/464113/</span>
<span class="hljs-keyword">import</span>  FreeCAD, FreeCADGui, Part, Draft
<span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">stamp</span>:</span>
    <span class="hljs-string">"This class creates a rectangle with text. Coordinates are set by entering into the console."</span>
    <span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">__init__</span>(<span class="hljs-params">self</span>):</span><font></font>
        self.view = FreeCADGui.ActiveDocument.ActiveView<font></font>
        x=float(input(<span class="hljs-string">"set x point  "</span>))<font></font>
        y=float(input(<span class="hljs-string">"set y point  "</span>))<font></font>
        mtext=str(input(<span class="hljs-string">"input text  "</span>))<font></font>
        self.drawstamp(mtext, x , y )<font></font>
        FreeCAD.Console.PrintMessage(<span class="hljs-string">"\r\n Your object was successfully created"</span>)<font></font>
      <font></font>
    <span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">drawstamp</span>(<span class="hljs-params">self, mtext,x=<span class="hljs-number">0</span>,y=<span class="hljs-number">0</span> </span>):</span>
        <span class="hljs-string">"Method for placing a figure in model space."</span>
        <span class="hljs-keyword">if</span> (mtext==<span class="hljs-string">""</span>):<font></font>
            mtext=<span class="hljs-string">"Hello Habr!"</span>
        point=FreeCAD.Placement(FreeCAD.Vector(x,y,<span class="hljs-number">0</span>), FreeCAD.Rotation(<span class="hljs-number">0</span>,<span class="hljs-number">0</span>,<span class="hljs-number">0</span>), FreeCAD.Vector(<span class="hljs-number">0</span>,<span class="hljs-number">0</span>,<span class="hljs-number">0</span>))<font></font>
        text = Draft.makeText(mtext,point=FreeCAD.Vector(x+<span class="hljs-number">0.25</span>,y+<span class="hljs-number">0.55</span>,<span class="hljs-number">0.0</span>))<font></font>
        fontsize = <span class="hljs-number">1.0</span>
        textwidth=(len(mtext)*fontsize*<span class="hljs-number">0.6</span>)+<span class="hljs-number">0.35</span>
        textheight=fontsize+<span class="hljs-number">0.5</span><font></font>
        text.ViewObject.FontSize = fontsize  <font></font>
        text.ViewObject.FontName = <span class="hljs-string">"Courier"</span>  
        rec = Draft.makeRectangle(length=textwidth,height=textheight,placement=point,face=<span class="hljs-literal">False</span>,support=<span class="hljs-literal">None</span>)</code></pre><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
または、</font></font><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">GitHub</font></font></a> <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">からファイルを単純にコピーすることもでき</font><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="><font style="vertical-align: inherit;">ます。</font></a></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> 
コードは非常に単純ですが、いくつかの点を明確にする必要があると思います。</font></font><br>
<br>
<pre><code class="python hljs"><span class="hljs-keyword">import</span>  FreeCAD, FreeCADGui, Part, Draft</code></pre><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
必要なライブラリをインポートして、クラスを作成します。</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
マウス入力の処理方法をまだ学習していないため、オブジェクトの座標とテキストをキーボードからコンソールに直接入力します。</font><font style="vertical-align: inherit;">これは、標準のPythonメソッドによって実装されます。</font><font style="vertical-align: inherit;">次に、クラスのコンストラクターで関数（メソッド）を呼び出し、すべてを描画します。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
クラスコンストラクターのFreeCADの機能のうち、2つのコマンドを区別できます。</font></font><br>
<br>
<pre><code class="python hljs">self.view = FreeCADGui.ActiveDocument.ActiveView<font></font>
FreeCAD.Console.PrintMessage(<span class="hljs-string">"\r\n Your object was successfully created"</span>)</code></pre><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
1つ目はアクティブなワークスペースのスペースを選択し、2つ目はオブジェクトをインストールした後、プログラムウィンドウの一番下（灰色のバーに、Pythonコンソールと混同しないように）にメッセージを書き込み</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ます。メソッドコードも直感的ですが、信頼性について説明します。</font></font><br>
<br>
<pre><code class="python hljs">    <span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">drawstamp</span>(<span class="hljs-params">self, mtext,x=<span class="hljs-number">0</span>,y=<span class="hljs-number">0</span> </span>):</span>
        <span class="hljs-string">"Method for placing a figure in model space."</span>
        <span class="hljs-keyword">if</span> (mtext==<span class="hljs-string">""</span>):<font></font>
            mtext=<span class="hljs-string">"Hello Habr!"</span></code></pre><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ユーザーが空の文字列を入力する場合に必要です。</font><font style="vertical-align: inherit;">これがないと、ラベルという単語がテキストに入力され、長方形の長さが正しくなくなります。</font></font><br>
<pre><code class="python hljs">point=FreeCAD.Placement(FreeCAD.Vector(x,y,<span class="hljs-number">0</span>), FreeCAD.Rotation(<span class="hljs-number">0</span>,<span class="hljs-number">0</span>,<span class="hljs-number">0</span>), FreeCAD.Vector(<span class="hljs-number">0</span>,<span class="hljs-number">0</span>,<span class="hljs-number">0</span>))</code></pre><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
テキストを囲むフレームのその日の基点の座標を定義します。</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
データはコンソールからの入力から取得されることを思い出させてください。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ここでは、FreeCAD.Vector（x、y、z）という形式の3次元座標を使用していますが、この例ではZ座標を無視できることに注意してください。</font><font style="vertical-align: inherit;">フレームの回転に関連する他のパラメーターは影響を受けません。</font></font><br>
<br>
<pre><code class="python hljs">text = Draft.makeText(mtext,point=FreeCAD.Vector(x+<span class="hljs-number">0.25</span>,y+<span class="hljs-number">0.55</span>,<span class="hljs-number">0.0</span>))</code></pre><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
Draft.makeTextコマンドを使用してテキストを作成し、コンソールに入力したテキストを渡します。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
フレームの基点から少しオフセットした座標を取得します。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
良い方法では、APIパラメータを使用してテキストのフレーム（境界）を処理し、それに基づいてフレーミングフレームの幅と高さを計算する方法を学ぶ必要がありました。</font><font style="vertical-align: inherit;">でも、私はプログラムに慣れたばかりなので、作業農法で解決しました。</font><font style="vertical-align: inherit;">フォントの高さを修正し、モノスペースフォント（Courier）のスタイルを割り当てます。これに応じて、テキストの周囲に描画するフレームの長さと幅を決定します。</font></font><br>
<br>
<pre><code class="python hljs">        text = Draft.makeText(mtext,point=FreeCAD.Vector(x+<span class="hljs-number">0.25</span>,y+<span class="hljs-number">0.55</span>,<span class="hljs-number">0.0</span>))<font></font>
        fontsize = <span class="hljs-number">1.0</span>
        textwidth=(len(mtext)*fontsize*<span class="hljs-number">0.6</span>)+<span class="hljs-number">0.35</span>
        textheight=fontsize+<span class="hljs-number">0.5</span><font></font>
        text.ViewObject.FontSize = fontsize  <font></font>
        text.ViewObject.FontName = <span class="hljs-string">"Courier"</span>  </code></pre><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
長方形の描画関数でパラメーターを置き換えるだけです。</font></font><br>
<br>
<pre><code class="python hljs">rec = Draft.makeRectangle(length=textwidth,height=textheight,placement=point,face=<span class="hljs-literal">False</span>,support=<span class="hljs-literal">None</span>)</code></pre><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
それが実際にすべてです。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ライブラリを接続するだけです。</font><font style="vertical-align: inherit;">これを行うには、選択した環境の残りのPythonライブラリが配置されているフォルダーにコピーするだけです。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
たとえば、次のようにWindowsの10のために、パスをすることができ</font></font><i><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">（</font></font></i><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> 
依存</font><i><font style="vertical-align: inherit;">アナコンダがインストールされている場所で）：</font></i><font style="vertical-align: inherit;"> C：\ Users \ユーザーYourUsernameName \ Anaconda3 \ ENVS \ FreeCADの\ Libの</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
Linuxの場合、パスはこのようなものになります：</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
/ホーム/ ourUserName / anaconda3 / ENVS / FreeCADの/ lib / python3.7あと</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
はライブラリをロードするだけです。</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
これを行うには、最初にコンソールにモジュールの名前を入力します（ファイル拡張子なし）。</font></font><br>
<br>
<pre><code class="python hljs"><span class="hljs-keyword">import</span> drawhabr</code></pre><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
そしてクラスコンストラクタを呼び出します </font></font><br>
<br>
<pre><code class="python hljs">drawhabr.stamp()</code></pre><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
リード、関数パラメーター、結果を楽しむために必要なことはこれだけです。</font></font><br>
<br>
<img src="https://habrastorage.org/webt/fp/h5/xo/fph5xoo0pduxfu2cjzvloyoluqg.png"><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
念のため、以下はすべてがLinuxでも機能することを確認するスクリーンショットです。</font></font><br>
<br>
<img src="https://habrastorage.org/webt/wh/ev/fi/whevfiwrqsnavzonawithlecqxk.png"><br>
<br>
<a name="V"></a><br>
<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> パートV：結論 </font></font></h4><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
今日、私たちはFreeCAD APIを理解するための小さな一歩を踏み出しました。</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
私の意見では、2次元の描画とプロジェクトの開発では、FreeCADはAutoCAD（NanoCAD）や他の一般的なCADシステムほど馴染みが薄いですが、プログラミングははるかに簡単です。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
ドキュメントが不足していて、Wiki FreeCADの例でいくつかの記事を更新する必要があるにもかかわらず、Pythonコードを書く知識がほとんどない未準備の人でも、APIを理解して最初のプログラムを実行することができました。</font></font><br>
<br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
そして、開発者は貪欲ではなく、必要に応じて、LGPLライセンスの下でFreeCADを使用し、Pythonライブラリのすべての能力（たとえば、同じAnaconda配布キットから）と組み合わせて商用開発を許可するという事実を考えると、FreeCADを使用したプログラムの開発は興味深いようですチャレンジ。</font></font><br><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
あなたがこのトピックに興味を持っていると私が理解した場合、Nanocadとの類推によってノートのミニサイクルを作ってみます</font></font><br>
<a name="VI"></a><br>
<div class="spoiler"><b class="spoiler_title"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">NanoCADプログラミングシリーズ</font></font></b><div class="spoiler_text"><ul>
<li><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="> «  »     Multicad.NET API 7 ( Nanocad 8.1)</a></li>
<li><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="> «    »   «-3D»   NanoCAD   MultiCAD.NET API</a></li>
<li><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="> «   »    CADa  SCADA (MultiCAD.NET API)</a></li>
<li><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="> «  »    NanoCAD  Linux (MultiCAD.NET API)</a></li>
<li><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="> «  —  !»   NanoCAD   Visual Basic .NET</a></li>
<li><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=aue&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=ja&amp;u="> «… ,  »       NanoCAD  C# (MultiCAD .NET API)<br>
</a></li>
</ul></div></div></div>
      
    </div>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../ja464103/index.html">OpenUNBドラフトナショナルIoT標準：批評的レビュー</a></li>
<li><a href="../ja464105/index.html">Docker Composeを備えたネイティブCommentoサーバー</a></li>
<li><a href="../ja464107/index.html">8月19日から25日までのモスクワでのデジタルイベント</a></li>
<li><a href="../ja464109/index.html">宇宙超音速パラシュート</a></li>
<li><a href="../ja464111/index.html">Natas Web。Webの脆弱性の悪用を目的としたCTFプラットフォームの通過</a></li>
<li><a href="../ja464115/index.html">デザイナー、レイアウトデザイナー、「Figma」をデザインシステム、バール、なんらかのマザー™を使用して友達にする方法</a></li>
<li><a href="../ja464117/index.html">クリスカスペルスキーとして知られるニコライリハチェフの父ウラジミールリハチェフを訪問</a></li>
<li><a href="../ja464121/index.html">先週フロントエンドの世界からの新鮮な食材のダイジェストNo.376（2019年8月12日〜18日）</a></li>
<li><a href="../ja464123/index.html">RSトリガーへの別のアプローチ、TLA +</a></li>
<li><a href="../ja464125/index.html">Googleの4,000語のプライバシーポリシーにおける秘密のインターネットストーリー</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter63335242 = new Ya.Metrika({
                  id:63335242,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/63335242" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134228602-13', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

<footer class="page-footer">
  <div class="page-footer-legal-info-container page-footer-element">
    <p>
      Geek Week | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2020</span>
    </p>
  </div>
  <div class="page-footer-counters-container page-footer-element">
    <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=i62cJ2037o_BACd40gCrIso3niu0Sjx2sDFYJkeYdRk&co=3a3a3a&ct=ffffff'/></a>
  </div>
</footer>
  
</body>

</html>